
MYDOCKER3_PATH=${MYDOCKER3_PATH:-$HOME/.mydocker3}
MYDOCKER3_HOME=${MYDOCKER3_HOME:-$HOME}
#MYDOCKER3_PATH=${MYDOCKER3_PATH:-$HOME/mydocker3/.mydocker3}
#MYDOCKER3_HOME=${MYDOCKER3_HOME:-$HOME/mydocker3}

#MYDOCKER3_PASSWORD=aa
#export PACK_PASSWORD="$MYDOCKER3_PASSWORD"

export MYDOCKER3_PATH
export MYDOCKER3_HOME

